### ISSUE TITLE
Android build failure - com.google.android.gms:play-services

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#120]
Using pushwoosh-cordova-plugin 3.6.5-1 from npmjs.org.

```
ANDROID_HOME=/Users/zarko/android/sdk-mac_x86
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home
Running: /Users/zarko/repos/int/app-container/platforms/android/gradlew cdvBuildDebug -b /Users/zarko/repos/int/app-container/platforms/android/build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services/
         file:/Users/zarko/android/sdk-mac_x86/extras/android/m2repository/com/google/android/gms/play-services/maven-metadata.xml
         file:/Users/zarko/android/sdk-mac_x86/extras/android/m2repository/com/google/android/gms/play-services/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.791 secs

/Users/zarko/repos/int/app-container/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/zarko/repos/int/app-container/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/zarko/repos/int/app-container/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/zarko/repos/int/app-container/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/zarko/repos/int/app-container/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/zarko/.nvm/v0.12.7/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by shaders** [comment]
Make sure your Android SDK is up to date.

http://stackoverflow.com/questions/19922107/gradle-unable-to-resolve-play-services-dependency
