### ISSUE TITLE
SyntaxError: Unexpected token when installing into ionic 1.6.5

### ISSUE THREAD

**Issue by mlevin2** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#130]
At the recommendation of Pushwoosh support, I attempted to update the plugin in my ionic project because I was getting a bunch of compiler warnings for iOS. I uninstalled the plugin first and then installed it with the command `ionic plugin add https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin.git` and got this:

``
Updated the hooks directory to have execute permissions
Fetching plugin "https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin.git" via git clone
Repository "https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin.git" checked out to git ref "master".
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Function.PlatformJson.load (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/PlatformJson.js:35:21)
    at runInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:273:37)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:84:16
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:408:9)
``

Does anyone have any suggestions?

Thanks

**Comment by mlevin2** [comment]
Disregard. Error was caused by something else.
