### ISSUE TITLE
Fatal exception on Message receive with app in foreground

### ISSUE THREAD

**Issue by PauloJf** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#133]
Hi getting a fatal exception on phonegap build when receiving a push with the app in foregroun, if app is in background all is fine.

10-22 00:04:34.111 E/AndroidRuntime(17039): FATAL EXCEPTION: main
10-22 00:04:34.111 E/AndroidRuntime(17039): Process: com.gatoserio.agendacmp, PID: 17039
10-22 00:04:34.111 E/AndroidRuntime(17039): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.gatoserio.agendacmp.action.PUSH_MESSAGE_RECEIVE flg=0x10 (has extras) } in com.pushwoosh.plugin.pushnotifications.PushNotifications$3@2686bef3
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:905)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at android.os.Handler.handleCallback(Handler.java:810)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at android.os.Looper.loop(Looper.java:189)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at android.app.ActivityThread.main(ActivityThread.java:5529)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at java.lang.reflect.Method.invoke(Native Method)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at java.lang.reflect.Method.invoke(Method.java:372)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
10-22 00:04:34.111 E/AndroidRuntime(17039): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at com.pushwoosh.BasePushMessageReceiver.handlePush(Unknown Source)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at com.pushwoosh.BasePushMessageReceiver.onReceive(Unknown Source)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:895)
10-22 00:04:34.111 E/AndroidRuntime(17039): 	... 8 more

Thanks

**Comment by PauloJf** [comment]
Confirm fix in 3.6.13, thanks :)
